In [8]:
import pandas as pd
import geopandas as gpd
import leafmap.foliumap as leafmapfol
import leafmap
import ast
import geopandas as gpd
from shapely.geometry import Polygon
import datacube
from odc.ui import with_ui_cbk
from deafrica_tools.plotting import rgb, display_map

%matplotlib inline
import matplotlib.pyplot as plt
from datacube.utils import geometry

from deafrica_tools.datahandling import load_ard
from deafrica_tools.bandindices import calculate_indices
from deafrica_tools.plotting import rgb, map_shapefile
from deafrica_tools.spatial import xr_rasterize
from deafrica_tools.classification import HiddenPrints
from odc.io.cgroups import get_cpu_quota
from deafrica_tools.classification import collect_training_data

import numpy as np
import xarray as xr
from odc.algo import xr_reproject
from pyproj import Proj, transform
from datacube.utils.geometry import assign_crs
from datacube.testutils.io import rio_slurp_xarray
from deafrica_tools.bandindices import calculate_indices
from deafrica_tools.dask import create_local_dask_cluster
pd.set_option('display.max_colwidth', 500)
from odc.algo import xr_geomedian

# datacube init

In [4]:
dc = datacube.Datacube(app='training_data_extraction')

In [3]:
product = "s2_l2a"
measurements = dc.list_measurements()
measurements.loc[product]

,name,dtype,units,nodata,aliases,flags_definition
measurement,,,,,,
B01,B01,uint16,1,0.0,"[band_01, coastal_aerosol]",NaN
B02,B02,uint16,1,0.0,"[band_02, blue]",NaN
B03,B03,uint16,1,0.0,"[band_03, green]",NaN
B04,B04,uint16,1,0.0,"[band_04, red]",NaN
B05,B05,uint16,1,0.0,"[band_05, red_edge_1]",NaN
B06,B06,uint16,1,0.0,"[band_06, red_edge_2]",NaN
B07,B07,uint16,1,0.0,"[band_07, red_edge_3]",NaN
B08,B08,uint16,1,0.0,"[band_08, nir, nir_1]",NaN
B8A,B8A,uint16,1,0.0,"[band_8a, nir_narrow, nir_2]",NaN
B09,B09,uint16,1,0.0,"[band_09, water_vapour]",NaN
B11,B11,uint16,1,0.0,"[band_11, swir_1, swir_16]",NaN
B12,B12,uint16,1,0.0,"[band_12, swir_2, swir_22]",NaN
SCL,SCL,uint8,1,0.0,"[mask, qa]","{'qa': {'bits': [0, 1, 2, 3, 4, 5, 6, 7], 'values': {'0': 'no data', '1': 'saturated or defective', '2': 'dark area pixels', '3': 'cloud shadows', '4': 'vegetation', '5': 'bare soils', '6': 'water', '7': 'unclassified', '8': 'cloud medium probability', '9': 'cloud high probability', '10': 'thin cirrus', '11': 'snow or ice'}, 'description': 'Sen2Cor Scene Classification'}}"
AOT,AOT,uint16,1,0.0,[aerosol_optical_thickness],NaN
WVP,WVP,uint16,1,0.0,[scene_average_water_vapour],NaN

## Read vector file

In [9]:
crop_vectors = gpd.read_file('../Numeric data models/data/crop_vectors_v4.geojson')

,id,culture,field,area,geometry
0,0,blé dur,0,0.487814,"POLYGON ((-8.63641 32.44224, -8.63746 32.44299, -8.63775 32.44275, -8.63674 32.44201, -8.63644 32.44223, -8.63641 32.44224))"
1,1,blé dur,0,1.181048,"POLYGON ((-8.63893 32.44024, -8.64091 32.44208, -8.64115 32.44193, -8.64075 32.44143, -8.64027 32.44089, -8.63980 32.44037, -8.63926 32.43997, -8.63892 32.44025, -8.63893 32.44024))"
2,2,blé dur,0,1.870528,"POLYGON ((-8.64332 32.43410, -8.64442 32.43408, -8.64449 32.43389, -8.64477 32.43354, -8.64590 32.43231, -8.64598 32.43225, -8.64539 32.43194, -8.64445 32.43294, -8.64398 32.43342, -8.64334 32.43409, -8.64332 32.43410))"
3,3,blé dur,0,1.726738,"POLYGON ((-8.64965 32.41717, -8.65039 32.41813, -8.65073 32.41794, -8.65201 32.41931, -8.65238 32.41973, -8.65268 32.41951, -8.65180 32.41850, -8.64999 32.41684, -8.64967 32.41717, -8.64965 32.41717))"
4,4,blé dur,0,1.429490,"POLYGON ((-8.67498 32.42193, -8.67550 32.42170, -8.67503 32.42087, -8.67260 32.42043, -8.67270 32.42060, -8.67448 32.42137, -8.67463 32.42145, -8.67496 32.42194, -8.67498 32.42193))"
...,...,...,...,...,...
2350,2350,pomme de terre,6,0.260809,"POLYGON ((-7.75747 32.80539, -7.75690 32.80535, -7.75681 32.80577, -7.75728 32.80589, -7.75747 32.80539))"
2351,2351,pomme de terre,6,3.981583,"POLYGON ((-7.88815 33.03053, -7.88710 33.02738, -7.88862 33.02721, -7.88907 33.02986, -7.88815 33.03053))"
2352,2352,pomme de terre,6,0.237408,"POLYGON ((-7.89247 33.03686, -7.89225 33.03705, -7.89290 33.03754, -7.89312 33.03736, -7.89247 33.03686))"
2353,2353,pomme de terre,6,0.469451,"POLYGON ((-7.89698 33.03398, -7.89752 33.03381, -7.89714 33.03311, -7.89659 33.03323, -7.89698 33.03398))"
2354,2354,pomme de terre,6,2.051135,"POLYGON ((-7.89730 33.02893, -7.89706 33.02847, -7.89762 33.02806, -7.89769 33.02768, -7.89787 33.02725, -7.89830 33.02699, -7.89870 33.02704, -7.89894 33.02720, -7.89915 33.02749, -7.89953 33.02776, -7.89873 33.02802, -7.89730 33.02893))"

## Define feature layers

In [10]:
query

{'time': ('2018-10-01', '2019-07-31'),
 'measurements': ['blue',
  'green',
  'red',
  'nir',
  'swir_1',
  'swir_2',
  'red_edge_1',
  'red_edge_2',
  'red_edge_3'],
 'resolution': (-10, 10),
 'output_crs': 'EPSG:6933',
 'group_by': 'solar_day',
 'resampling': 'bilinear'}

In [ ]:
ds = load_ard(
        dc=dc,
        x=(-11.50, -11.47),
        y=(21.00, 21.04),
        products=["s2_l2a"],
        verbose=False,
        **query)

In [ ]:
def geomedian_with_indices_wrapper(ds):
    """Apply xr_geomedian function and calculate a series of indices"""

    indices = ["NDVI", "LAI", "SAVI", "MSAVI", "NDMI"]
    satellite_mission = "s2"

    ds_geomedian = xr_geomedian(ds)

    ds_geomedian = calculate_indices(
        ds_geomedian,
        index=indices,
        drop=False,
        satellite_mission=satellite_mission,
    )

    return ds_geomedian

In [ ]:
time_ranges = {
        "18_1": slice("2018-10-01", "2018-12-31"),
        "19_1": slice("2019-01-01", "2019-03-31"),
        "19_2": slice("2019-04-01", "2019-06-31"),
        "19_3": slice("2019-07-01", "2019-07-31")}
s2_geomad_list = apply_function_over_custom_times(ds, geomedian_with_indices_wrapper, "s2", time_ranges)

##### Biannual geomedian (extent : september - july)

In [10]:
#QUERY
time_range = ('2018', '2019')
measurements = ["blue", "green", "red", "nir", "swir_1", "swir_2", "red_edge_1", "red_edge_2", "red_edge_3", "sdev", "bcdev", "edev"]
resolution = (-10,10)
output_crs = 'EPSG:6933'
query = {'time': time_range, 'measurements': measurements, 'resolution': resolution, 'output_crs': output_crs, 'group_by' : 'solar_day', 'resampling': 'bilinear'}

In [11]:
def feature_layer(ds, era):
    
    # Normalize bands 
    for band in ds.data_vars:
        if band not in ["sdev", "bcdev"]:
            ds[band] = ds[band] / 10000

    # Add indices
    feature_data = calculate_indices(
        ds,
        index=["NDVI", "LAI", "EVI", "SAVI", "NDMI"],
        drop=False,
        normalise=False,
        collection="s2",
    )
    
    # Normalize geomads using log
    feature_data["sdev"] = -np.log(feature_data["sdev"])
    feature_data["bcdev"] = -np.log(feature_data["bcdev"])
    feature_data["edev"] = -np.log(feature_data["edev"])
    
    for band in feature_data.data_vars:
        feature_data = feature_data.rename({band: band + era})
    
    return feature_data


def experiment_gm_n_n1(query):
    
    # Connect to the datacube
    dc = datacube.Datacube(app='feature_layers')
    
    # load S2 geomedian
    ds = dc.load(product='gm_s2_semiannual', **query)
    
    # load the data
    dss = {"S1": ds.isel(time=1),
           "S2": ds.isel(time=2), }
    
    # Create features
    epoch1 = feature_layer(dss["S1"], era="_S1")
    epoch2 = feature_layer(dss["S2"], era="_S2")

    result = xr.merge([epoch1, epoch2], compat="override")

    return result.astype(np.float32).squeeze()

##### Custom geomedian (extent: september - July)

In [9]:
#QUERY
time_range = ('2018-10-01', '2019-07-31')
measurements = ["blue", "green", "red", "nir", "swir_1", "swir_2", "red_edge_1", "red_edge_2", "red_edge_3"]
resolution = (-10,10)
output_crs = 'EPSG:6933'
query = {'time': time_range, 'measurements': measurements, 'resolution': resolution, 'output_crs': output_crs, 'group_by' : 'solar_day', 'resampling': 'bilinear'}

In [ ]:
ds = load_ard(
        dc=dc,
        products=["s2_l2a"],
        measurements=s2_measurements,
        group_by="solar_day",
        verbose=False,
        **query,
    )

# Apply geomedian over time ranges and calculate band indices
s2_geomad_list = apply_function_over_custom_times(ds, geomedian_with_indices_wrapper, "s2", time_ranges)

In [ ]:
def geomedian_with_indices_wrapper(ds):
    """Apply xr_geomedian function and calculate a series of indices"""

    indices = ["NDVI", "LAI", "SAVI", "MSAVI", "NDMI"]
    satellite_mission = "s2"

    ds_geomedian = xr_geomedian(ds)

    ds_geomedian = calculate_indices(
        ds_geomedian,
        index=indices,
        drop=False,
        satellite_mission=satellite_mission,
    )

    return ds_geomedian


def feature_layers(query):
    """Compute feature layers according to datacube query"""

    # Connnect to datacube
    dc = datacube.Datacube(app="crop_type_ml")
    
    time_ranges = {
        "18_1": slice("2018-10-01", "2018-12-31"),
        "19_1": slice("2019-01-01", "2019-03-31"),
        "19_2": slice("2019-04-01", "2019-06-31"),
        "19_3": slice("2019-07-01", "2019-07-31")
    }

    ds = load_ard(
        dc=dc,
        products=["s2_l2a"],
        group_by="solar_day",
        verbose=False,
        **query,
    )

    # Apply geomedian over time ranges and calculate band indices
    s2_geomad_list = apply_function_over_custom_times(
        ds, geomedian_with_indices_wrapper, "s2", time_ranges
    )

## Extracting multispectral data

In [ ]:
%%time
#zonal_stats = 'median'
return_coords = True
field = 'field'
ncpus=round(get_cpu_quota())
print('ncpus = '+str(ncpus))

column_names, array_values = collect_training_data(gdf=crop_vectors,
                                                    dc_query=query,
                                                    ncpus=15,
                                                    clean=False,
                                                    return_coords=return_coords,
                                                    field=field,
                                                    #zonal_stats=zonal_stats,
                                                    fail_threshold=0.0075,
                                                    feature_func=experiment_gm_n_n1)